service:
  collection:
    suggestion: suggestion
    comment: comment
    user: user
  password.expiration: 864_000_000 # expiration of auth token
azure.keyvault.enabled: false
spring.data.mongodb:
  database: tracker
